Allow support for alternate AWS profiles.
ember-cli-deploy/ember-cli-deploy-s3 pull request #71
Opened 2016-09-20 14:01 UTC by seanstar12

## What Changed & Why
Added variable and condition check to allow the swapping of AWS profiles.

## PR Checklist
- [ ] Add tests -- Config is already tested for errors. Error(s) would occur in AWS-SDK.
- [x] Add documentation
- [ ] Prefix documentation-only commits with [DOC]

2016-09-21 07:51 UTC, achambers approved these changes

2016-09-21 07:53 UTC, achambers commented on README.md
> +### profile
Could you please change the commit message that contains this documentation change to begin with `[DOC]` ?

2016-09-21 07:53 UTC, achambers requested changes

2016-09-21 08:30 UTC, seanstar12 commented on README.md
> +### profile
Change has been made.

2016-09-21 15:47 UTC, achambers approved these changes

2016-09-21 15:48 UTC, merged

2016-09-21 15:48 UTC, achambers commented
Thanks @seanstar12 . I'll try and get this released shortly.

2016-10-04 03:46 UTC, seanstar12 commented
@achambers Thanks! Any word on when it will be pushed to npm?