Update ember cli 2.10
ember-cli-deploy/ember-cli-deploy-s3 pull request #80
Opened 2016-12-16 19:09 UTC by jrjohnson

## What Changed & Why
In the interests of staying current I updated dependancies and blueprints for ember-cli 2.10.0.  The only material changes made were to tests/unit/index-nodetest.js and tests/unit/lib/s3-nodetest.js where I copied the advised template from http://ember-cli-deploy.com/docs/v0.6.x/writing-a-plugin/

2016-12-16 19:17 UTC, lukemelia commented
@jrjohnson This looks good. As discussed in Slack, I'd ultimately like to remove standard files that serve no purpose in this addon. e.g. stuff related to qunit/in-browser testing. That should be a separate PR anyway, though.

2016-12-16 19:18 UTC, lukemelia requested changes

2016-12-16 19:18 UTC, lukemelia commented on .travis.yml
> -  - npm test
@jrjohnson this change is not appropriate because it makes travis try to run ember tests instead of the node tests specified in package.json.

2016-12-16 19:45 UTC, jrjohnson commented on .travis.yml
> -  - npm test
Damn.  I fixed that.  Must have gotten lost when I was messing with what to include / not include in this PR. Good catch.  Sorry.  I pushed the fix, should I squash commits?  Or do you prefer them separate?

2016-12-16 19:47 UTC, jrjohnson commented
@lukemelia yes.  I was thinking I would sweep through several plugins and update ember-cli and then go back through and start pulling out things like ember-try, qunit, etc... that are not being used.  Also not included here is that JSHint isn't running in CI so some errors are not being caught - but that seems like a different PR as well.

2016-12-22 17:09 UTC, lukemelia approved these changes

2016-12-22 17:09 UTC, merged